### ISSUE TITLE
Additional tabs when using :tabopen

### ISSUE THREAD

**Issue by dfkamm** [tridactyl/tridactyl#1237]
Since updating to Firefox 64, sometimes when using :tabopen, one to three additional blank tabs will open alongside the tab I intended to open.

This occurs using Firefox 64 on Ubuntu 18.04.

**Comment by bovine3dom** [comment]
I haven't noticed this on Windows. I'll keep an eye out for it on Linux tomorrow. Thanks for reporting.

**Comment by antonva** [comment]
Can confirm that this happens, haven't found a reliable way to reproduce it yet.
As a side note, 64 is peppered with errors in the browser console, some even caused by us!

**Comment by glacambre** [comment]
I think https://github.com/tridactyl/tridactyl/issues/1167 also reported this bug.

**Comment by bovine3dom** [comment]
I've been experiencing this on Windows now. I keep finding tabs open on www.google.com, so presumably we're trying to search for an empty string?

**Comment by glacambre** [comment]
I've been able to reliably reproduce this bug for a short while.
1) It seemed to happen only when I typed the same query fast enough while being in the tab the bug originally happened in
2) The tabopen alias I created in order to log tabopen calls was called thrice
3) According to the logs, the two other tabs were opened before the one I wanted (which is weird, given the order they get in Firefox's tab bar)
4) After setting a breakpoint at commandline_frame.ts:155, the tab I tried to open wouldn't until I resumed execution while the two others did instantly, without hitting the breakpoint

**Comment by glacambre** [comment]
If you're running the Tridactyl betas, please update and restart Firefox. #1243 might have fixed this issue, if you can still reproduce it after updating please let us know. Otherwise we'll probably close this issue in a week.

**Comment by dfkamm** [comment]
Oh no, don't worry; you were perfectly clear, I'm the one who should have been less vague! Yes, I updated Tridactyl and restarted Firefox, my version is `1.14.6-8-g065d957` though?

**Comment by glacambre** [comment]
Oh, you have the right version, I'm the one behind the times.

I think the problem might be that multiple Tridactyl versions are running at the same time. It might be caused by our update-disabling mechanism. I'll see if we can do something about it.

**Comment by glacambre** [comment]
We tried another fix, please let us know if you can still reproduce this bug after upgrading to 1.14.6-10-gcee8cb0 or better.

**Comment by dfkamm** [comment]
Have updated to 1.14.6-10-gcee8cb0, and the bug seems to occur less frequently, but is still present.

**Comment by bovine3dom** [comment]
I seem to see this at the same time as #1239, neither `p` nor `P` work in the tab either.

**Comment by sajaysurya** [comment]
I just updated to 1.14.8. The problem still persists. It is repeatable when I open a new tab with gmail as the current tab. I'm the one who raised #1330.

**Comment by cmcaine** [comment]
So this turned out to be a Firefox bug as discovered and documented by glacambre in #760.

We can probably add a guard to our scripts that tests if they have already run. There's an issue with Firefox losing global (window) vars on history back, but we can probably come up with something.

We just need to avoid adding duplicate listeners, I think.

**Comment by glacambre** [comment]
We tried adding a guard [here](https://github.com/tridactyl/tridactyl/blob/10b3961b5ae821fb0fa1d6ca40216ae428c469f4/src/content.ts#L4-L7) but this was back when I wasn't aware that import statements were hoisted to the top of the script, which makes this lock sort of useless. We probably need to add this check to every file that has an influence on Tridactyl's state :(

**Comment by saulrh** [comment]
Oh, cool, we get to #ifndef everything we own just like the old days. :P

**Comment by bovine3dom** [comment]
I haven't seen this for a short while with 1.14.10. Perhaps it is fixed?

**Comment by dfkamm** [comment]
Nice, just updated. Looking good so far after some testing, but will see after a few hours if it's truly gone.

**Comment by dfkamm** [comment]
Yes, not fixed yet, but occurring much less frequently than before. In the two days since I updated, I've only had this happen once, so that's way better than it was before. Thanks to everyone who's been working on this.

**Comment by purgat0ri** [comment]
It seemed somewhat better after the update, but further tests have proven otherwise. I'm still seeing upwards of three tabs opening on some occasions.

**Comment by suyashbire1** [comment]
I have this problem too on Debian + Firefox 67.0.1 + Tridactyl 1.15.0. Haven't come across this in the thread but `winopen` occasionally opens three windows too.

**Comment by jpweytjens** [comment]
Is anyone else still experiencing this issue? I'm using Tridactyl version `1.16.1pre2946` and I haven't had multiple tabs open in a while, though I don't know how to test this behaviour in a controlled way.

**Comment by bovine3dom** [comment]
Yeah. We're pretty sure it's because we have multiple command lines on the page.

We're about 10% of the way done on rewriting it to try to fix it: https://github.com/cmcaine/tridactyl-2-experiments

**Comment by bovine3dom** [comment]
I haven't seen this for _ages_. Has anyone noticed it?

**Comment by paparomeo** [comment]
I've haven't seen it in ages either. I think it's fixed.

**Comment by dfkamm** [comment]
Can't remember the last time it's happened, so I would agree that it's fixed.
