### ISSUE TITLE
Slow URL editing in command-bar opened with Shift+O

### ISSUE THREAD

**Issue by gsbabil** [tridactyl/tridactyl#229]
Tridactyl allows opening the command-bar with the current URL by
pressing `Shift+O`. However, deleting, editing text etc. operations
in the current URL inside the command-bar opened by pressing
`Shif+O` is very slow.

**To Reproduce:**

1. Open [any new page][1]

2. Press `Shift+O` to open the command-bar with [current URL][1]

3. Press `backspace` or `delete` on the keyboard to delete certain
   parts of the URL inside the command-bar. The editing operation
   will be visibly slow in responsiveness.

**Expected Result:**

- URL editing operation inside the command-bar should be smooth as
  in editing a regular text-box, or at least as responsive as when
  the command-bar is opened by pressing just `O`.

[1]: https://github.com/cmcaine/tridactyl/issues/229

**Comment by bovine3dom** [comment]
I can't reproduce this on 6e9bf93, even on a slow machine.

Can you confirm that there is a difference between the performance of `O` and `o` if you paste the current URL into it?

**Comment by johnbeard** [comment]
Is the console open? I find holding backspace in the command line stutters when the developer panel is open, probably due to the large amount of logging happening (c.f. #206). Closing the panel makes it work OK.

**Comment by gsbabil** [comment]
Hi @bovine3dom, @johnbeard,

Thanks for the prompt reply. My current set-up is as follows:

  - **Firefox**   : `58.0b10`
  - **Tridactyl** : `1.7.0-40-g6e9bf93`

When I did the test above, I did *not* have Firefox's developer
console open. So at least for me, the slow responsiveness doesn't
necessarily seem to be coming from the heavy logging going on in the
Firefox developer console.

However, I just did another test with Firefox's developer console
turned on, and I can verify that there's indeed a large amount of
logging going on resulting into slow responsiveness for Tridactyl
command-bar opened both with `O` and `Shift+O`.

Hope this helps. Thank you.

P.S.

Is there a way to temporarily disable the logging going into
Firefox's developer-console? Thank you.

**Comment by gsbabil** [comment]
Also, after some more tests, it feels to me like slow responsiveness
is worse for URLs with a large number of positive match to display
in Tridactyl command-bar opened either with `O` or `Shift+O`.

The slow responsiveness isn't perceived in the Firefox's built-in
URL-bar for the same set of URLs resulting into many positive
matches.

Thank you.

**Comment by yourealwaysbe** [comment]
I notice a noticable slow down in the command line the more text i type.  In fact, as long as i'm typing the CPU usage of Firefox bumps up to 100% and stays there until a while after i stop typing (i tried typing for a long time).

This may be related as shift+O already starts with a full command line.

Vim Vixen has the same issue for me.  Also Firefox in general can be quite laggy, so it could possibly be an issue with Firefox.

I have Tridactyl 1.8.2, Firefox 58.0.2, and Arch Linux.  Tridactyl is my only active extension.

**Comment by gsbabil** [comment]
@yourealwaysbe 

> Vim Vixen has the same issue for me.

I confirm that I had the same "laggy" experience with `Vim Vixen`
during my testing.

Another hint I could share is that it feels less "laggy" on a fresh
Firefox profile with minimum history, bookmark etc.

Hope this helps. Thank you.

**Comment by bovine3dom** [comment]
I still can't reproduce this, even on a slow machine. CPU usage does go up a lot while typing rapidly though.

**Comment by yourealwaysbe** [comment]
@gsbabil if you add a space before the open command, it disables auto-completion and the slowdown goes away.  The completion definitely seems to be the problem

**Comment by cmcaine** [comment]
Completion isn't throttled at all, so this is plausible.

**Comment by gsbabil** [comment]
@yourealwaysbe

> if you add a space before the open command, it disables
> auto-completion and the slowdown goes away. The completion
> definitely seems to be the problem

Thanks for the tip.

@bovine3dom @cmcaine

I have uploaded a video [here][1] with the following description to
further illustrate the issue. The video is unlisted for obvious reasons.
Wish Github supported uploading WebM files!

Hope this helps. Thank you.


**Tridactyl (1.8.2-5-ge43f4fa) - slow URL editing and high CPU usage
  with Shift+O**

- https://youtu.be/nAL9_oM39Mo

- Between 00:00 - 00:02, the CPU usage is normal as expected

- At 00:03, `Shift+O` is pressed, and immediately `Backspace` is
  pressed to delete from the end of the URL in the Tridactyl
  command-bar

- Between 00:03 - 00:27, `Backspace` key is kept pressed.

- Please note the rather slow deletion of characters in the Tridacty
  command-bar

- At 00:28, `Backspace` key is released (URL edititing ends), and
  `Esc` is pressed to hide the Tridactyl command-bar.

- Please note the drop in CPU usage from 00:28 upto 00:59 (end of
  video)

[1]: https://youtu.be/nAL9_oM39Mo

**Comment by bovine3dom** [comment]
@gsbabil I think this might have been fixed along with #454, would you mind testing again? Thanks.

**Comment by bovine3dom** [comment]
Fixed in #1105. Cheers, glacambre!

**Comment by weskerfoot** [comment]
I'm still getting issues related to this.
1.14.8-129-g5e13b87

**Comment by bovine3dom** [comment]
Yeah, it's got worse again recently. We just need to kill the commandline with fire and think about how it should work seriously. That just takes time. It's the main thing I want out of #1379.

**Comment by weskerfoot** [comment]
@bovine3dom Thanks for the update. Awesome work by the way. I was a hardcore pentadactyl user before and really appreciate the effort being put into this.
