### ISSUE TITLE
Scrolling doesn't always scroll the right element (was: up/down doesn't work in Jupyter)

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#35]
All the other commands work, as far as I can tell.

**Comment by bovine3dom** [comment]
Additionally, d8e1eb450658ca64c42a6b597c8ff8badad68351 has broken the vim bindings, partically.

The sensible solution would be to have an ignore mode like Vimperator. Blocked by mode indicator.

A list of sites to automatically put into ignore mode could be nice.

**Comment by cmcaine** [comment]
Reddit with RES is also broken.

The whole suppression system is borked at the moment.

**Comment by cmcaine** [comment]
Fixed the issue with RES. RES's keybinds are just shadowed until you enter ignore mode or insert mode.

**Comment by glacambre** [comment]
I'm sorry, this was closed because I wrote "fix #35" in #488 but I think the issue is still there.

**Comment by cmcaine** [comment]
This page also scrolls wrong. https://nextjournal.com/jbieler/adding-static-type-checking-to-julia-in-100-lines-of-code/

I get a white border at the bottom of the page when scrolling with j.

**Comment by bovine3dom** [comment]
nextjournal and jupyter seem to work fine now
