### ISSUE TITLE
Transparency of the search bar and menu does not work with the "Dark Reader" extension

### ISSUE THREAD

**Issue by glowbigger** [tridactyl/tridactyl#4364]
-   Steps to reproduce: Install the "Dark Reader" extension. Use a theme like "midnight" and observe that there is no transparency between the menu and the bar when you press 'o'. There is no issue, however, on the new tab page where the dark reader extension is disabled.

-   Tridactyl version: 1.22.1

-   Firefox version: 103.0.2

**Comment by bovine3dom** [comment]
Fixed in #4576

**Comment by jasht1** [comment]
This still appears to be an issue, similarly to https://github.com/tridactyl/tridactyl/issues/4294 I use the [GruxBox Theme](https://github.com/jrolfs/gruvbox-material-tridactyl) which has some pretty large iframe containers. On any site where [darkreader](https://github.com/darkreader/darkreader) is active I still get the white boxes. 

This is potentially more relevant to darkreader so I have added a more comprehensive Issue [there](https://github.com/darkreader/darkreader/issues/14410), but I am also updating this thread for the sake of completeness.

- Tridactyl Version:  1.24.2
- LibreWolf Version: 139.0.4-1
&& 
- Firefox Version:  139.0.4 (64-bit)
