### ISSUE TITLE
guiset hoverlink top-right is permanent

### ISSUE THREAD

**Issue by kimat** [tridactyl/tridactyl#803]
version: 1.13.1-87-g2a43d0b

1. `guiset hoverlink top-right` in your `tridactylrc` then `:source` + `:restart` -> notice hoverlink is top-right above tabs
1. `guiset hoverlink right` in your `tridactylrc` then `:source` + `:restart` -> notice hoverlink is still top-right

A `cp userChrome.orig.css userChrome.css` can unstuck one.

**Comment by iago-lito** [comment]
Not sure if it's the same one here: Debian 4.9.88-1+deb9u1 (2018-05-07) with  firefox 61.0.1 and tridactyl 1.13.1-1.13.1 with native installed.

The `guiset hoverlink top-right` command seems ignored, even after `:restart`: hyperlinks are still shown bottom left and cover the command line, so the problem #40 remains.

**Comment by bovine3dom** [comment]
@iago-lito, yeah, it was fixed in #763. I want to do a stable release soon but the betas have some unpleasant bugs I'd like to sort out first.

**Comment by iago-lito** [comment]
Great. No worries :) Thank you for support!

**Comment by glacambre** [comment]
I can still reproduce this bug. I think it is caused by https://github.com/tridactyl/tridactyl/blob/0512c3e125db384b988cc4cf1b4f99820ea1632e/src/css_util.ts#L25 and https://github.com/tridactyl/tridactyl/blob/0512c3e125db384b988cc4cf1b4f99820ea1632e/src/css_util.ts#L32 . Not sure why this limitation is there and how to fix it though. I think we can't just remove the comma because it is necessary to support multiple firefox versions.

**Comment by bovine3dom** [comment]
If the change happened before ESR, I'm happy to remove support for it.
